config/routes.rb
Rails.application.routes.draw do
  resources :seminartopics
  devise_for :users
  root to: 'seminartopics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seminartopic.rb
class Seminartopic < ApplicationRecord
  belongs_to :user
  validates :title, presence: :true
  validates :descripton, presence: :true
end

app/controllers/seminartopics_controller.rb
class SeminartopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_seminartopic, only: [:show, :edit, :update, :destroy]

  # GET /seminartopics
  # GET /seminartopics.json
  def index
    @seminartopics = Seminartopic.all
  end

  # GET /seminartopics/1
  # GET /seminartopics/1.json
  def show
  end

  # GET /seminartopics/new
  def new
    @seminartopic = Seminartopic.new
  end

  # GET /seminartopics/1/edit
  def edit
  end

  # POST /seminartopics
  # POST /seminartopics.json
  def create
    @seminartopic = Seminartopic.new(seminartopic_params)

    respond_to do |format|
      if @seminartopic.save
        format.html { redirect_to @seminartopic, notice: 'Seminartopic was successfully created.' }
        format.json { render :show, status: :created, location: @seminartopic }
      else
        format.html { render :new }
        format.json { render json: @seminartopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seminartopics/1
  # PATCH/PUT /seminartopics/1.json
  def update
    respond_to do |format|
      if @seminartopic.update(seminartopic_params)
        format.html { redirect_to @seminartopic, notice: 'Seminartopic was successfully updated.' }
        format.json { render :show, status: :ok, location: @seminartopic }
      else
        format.html { render :edit }
        format.json { render json: @seminartopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seminartopics/1
  # DELETE /seminartopics/1.json
  def destroy
    @seminartopic.destroy
    respond_to do |format|
      format.html { redirect_to seminartopics_url, notice: 'Seminartopic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seminartopic
      @seminartopic = Seminartopic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seminartopic_params
      params.require(:seminartopic).permit(:title, :descripton, :studname, :user_id)
    end
end

app/helpers/seminartopics_helper.rb
module SeminartopicsHelper
end

app/views/seminartopics/_form.html.haml
= form_with(model: seminartopic, local: true) do |form|
  - if seminartopic.errors.any?
    #error_explanation.form-group
      %h2
        = pluralize(seminartopic.errors.count, "error")
        prohibited this seminartopic from being saved:
      %ul
        - seminartopic.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :title
    = form.text_field :title, autofocus: true, class: "form-control"
  .form-group
    = form.label :descripton
    = form.text_field :descripton, autofocus: true, class: "form-control"
  .form-group
    = form.label :StudentName
    = form.text_field :studname, autofocus: true, class: "form-control"
  .form-group
    = form.hidden_field :user_id, value:current_user.id
  .actions
    = form.submit class:"btn btn-primary"

app/views/seminartopics/edit.html.haml
%center
  %h1{style: "color:blue;"} Editing Seminartopic
  = render 'form', seminartopic: @seminartopic
  = link_to 'Show', @seminartopic, class: "btn btn-success"
  |
  \#{link_to 'Back', seminartopics_path, class: "btn btn-success"}

app/views/seminartopics/index.html.haml
%h1{style: "color:blue;"}
  %center Seminartopics
%br/
%table.table.table-bordered.table-stripped
  %thead
    %tr
      %th Title
      %th Descripton
      %th Username
      %th Studentname
      %th{colspan: "3"}
        %center Actions
  %tbody
    - @seminartopics.each do |seminartopic|
      %tr
        %td= seminartopic.title
        %td= seminartopic.descripton
        %td= User.find_by_id(seminartopic.user_id).try(:username)
        %td= seminartopic.try(:studname)
        %td= link_to 'Show', seminartopic, class: "btn btn-primary"
        %td= link_to 'Edit', edit_seminartopic_path(seminartopic), |
            class: "btn btn-primary"                              |
        %td
          = link_to 'Destroy', seminartopic, method: :delete, data: |
            { confirm: 'Are you sure?' }, class: "btn btn-danger"   |
.pull-right
  = link_to 'New Seminartopic', new_seminartopic_path, |
    class: "btn btn-success"                           |

app/views/seminartopics/new.html.haml
%h1{style: "color:blue;"} New Seminartopic
= render 'form', seminartopic: @seminartopic
= link_to 'Back', seminartopics_path, class: "btn btn-success"

app/views/seminartopics/show.html.haml
%center
  %h1{style: "color:blue;"}
    %center Seminartopic
  %p
    %strong Title:
    = @seminartopic.title
  %p
    %strong Descripton:
    = @seminartopic.descripton
  %p
    %strong Studentname:
    = @seminartopic.studname
  %p
    %strong User:
    = User.find_by_id(@seminartopic.user_id).try(:username)
  = link_to 'Edit', edit_seminartopic_path(@seminartopic), class: "btn btn-success"
  |
  = link_to 'Back', seminartopics_path, class: "btn btn-success"